---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating ec2 instance
      ec2:
        key_name: suite
        region: ap-southeast-1
        instance_type: t2.micro
        image: ami-106aa373
        wait: yes
        wait_timeout: 500
        exact_count: 1
        instance_tags:
           Name: suite
           User: '{{ user }}'
        count_tag:
           Name: suite
           User: '{{ user }}'
        vpc_subnet_id: subnet-b069ebd4
        group_id: sg-6c3e3408
        assign_public_ip: yes
      register: ec2

    - debug: var=ec2

    - name: Wait for SSH to come up
      wait_for:
        host: '{{ item.public_ip }}'
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: '{{ ec2.instances }}'

    - name: Refresh inventory
      meta: refresh_inventory

- hosts: tag_Name_suite
  remote_user: centos
  tasks:
    - name: Creating {{ user }} group
      become: yes
      become_user: root
      group:
          name: '{{ user }}'
          state: present

    - name: Creating {{ user }} user
      become: yes
      become_user: root
      user:
          name: '{{ user }}'
          group: '{{ user }}'
          password: '{{ password }}'
          update_password: always
          state: present

    - name: Enabling nopassword for {{ user }} when using sudo
      become: yes
      become_user: root
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%{{ user }}'
        line: '%{{ user }} ALL=(ALL) NOPASSWD: ALL'

    - name: Enabling PasswordAuthentication for {{ user }}
      become: yes
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        line: 'PasswordAuthentication yes'
        state: present

    - name: Restarting the SSH service
      become: yes
      service:
        name: sshd
        state: restarted
